version: "3"
services:
  api:
    image: api-db:0.3
    ports:
      - "3000:3000"
    networks:
      testing_net:
            ipv4_address: 182.18.7.9
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - PORT=3000
      - IP=182.18.7.2
      - PASS=123456789
      - USER=luigi
    depends_on:
      - mysql  
  mysql:
    container_name: mysql
    restart: always
    image: bd:0.12
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456789,
      MYSQL_DATABASE: company,
    networks:
        testing_net:
            ipv4_address: 182.18.7.2
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
        testing_net:
            ipv4_address: 182.18.7.3
    depends_on:
      - mysql

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 182.18.7.0/24